[package]
name = "nn"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.35", features = ["cargo", "derive"] }
dirs = "6.0.0"
jiff = "0.2.6"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.20"

[dev-dependencies]
tempfile = "3.7"
